#!/usr/bin/env bash
# Installs a packaged CARLA release (UE4) and the matching Python client into the repo venv.
#
#   scripts/install_carla.sh                         # 0.9.15 into ~/carla/CARLA_0.9.15
#   scripts/install_carla.sh 0.9.16 /opt/carla       # other version / directory
#   scripts/install_carla.sh 0.9.15 --from-tar ~/Downloads/CARLA_0.9.15.tar.gz \
#                                  --maps-tar ~/Downloads/AdditionalMaps_0.9.15.tar.gz
#
# Writes env.local.sh (CARLA_ROOT), which env.sh sources. Run scripts/setup.sh first (it creates the venv).
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
VERSION=0.9.15
DIR=""
TAR=""
MAPS_TAR=""
MAPS=1
VENV="$ROOT/.venv"
BASE_URL=${CARLA_BASE_URL:-https://carla-releases.s3.us-east-005.backblazeb2.com/Linux}

usage() { sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'; cat <<'EOF'
Options:
  VERSION                0.9.15 (default) or 0.9.16
  DIR                    install directory (default ~/carla/CARLA_<VERSION>)
  --from-tar FILE        use a downloaded CARLA_<VERSION>.tar.gz instead of downloading
  --maps-tar FILE        use a downloaded AdditionalMaps_<VERSION>.tar.gz
  --no-maps              skip the additional maps (Town06/07/10HD/12/13/15 ...)
  --venv DIR             venv that receives the carla wheel (default .venv)
Environment: CARLA_BASE_URL (default the official release bucket)
EOF
}

POS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --from-tar) TAR=$(realpath "$2"); shift 2 ;;
    --maps-tar) MAPS_TAR=$(realpath "$2"); shift 2 ;;
    --no-maps) MAPS=0; shift ;;
    --venv) VENV=$(realpath -m "$2"); shift 2 ;;
    -h|--help) usage; exit 0 ;;
    -*) echo "unknown option: $1"; usage; exit 2 ;;
    *) POS+=("$1"); shift ;;
  esac
done
[ ${#POS[@]} -ge 1 ] && VERSION=${POS[0]}
[ ${#POS[@]} -ge 2 ] && DIR=$(realpath -m "${POS[1]}")
DIR=${DIR:-$HOME/carla/CARLA_$VERSION}

download() {  # url dest
  if command -v wget >/dev/null; then wget -c -O "$2" "$1"; else curl -fL -C - -o "$2" "$1"; fi
}

echo "== CARLA $VERSION -> $DIR"
mkdir -p "$DIR"
if [ -x "$DIR/CarlaUE4.sh" ]; then
  echo "   already installed (CarlaUE4.sh present), skipping extraction"
else
  if [ -z "$TAR" ]; then
    TAR="$DIR/../CARLA_$VERSION.tar.gz"
    echo "   downloading $BASE_URL/CARLA_$VERSION.tar.gz (~16 GB)"
    download "$BASE_URL/CARLA_$VERSION.tar.gz" "$TAR" || {
      echo "download failed: get CARLA_$VERSION.tar.gz from https://github.com/carla-simulator/carla/releases"
      echo "and re-run with --from-tar FILE"; exit 1; }
  fi
  echo "   extracting $TAR"
  tar -xzf "$TAR" -C "$DIR"
  [ -x "$DIR/CarlaUE4.sh" ] || { echo "CarlaUE4.sh not found after extraction (wrong archive?)"; exit 1; }
  echo "   extracted; the archive can be deleted: rm $TAR"
fi

if [ $MAPS = 1 ]; then
  MARK="$DIR/.additional_maps_$VERSION"
  if [ -f "$MARK" ]; then
    echo "   additional maps already imported"
  else
    mkdir -p "$DIR/Import"
    if [ -z "$MAPS_TAR" ]; then
      MAPS_TAR="$DIR/Import/AdditionalMaps_$VERSION.tar.gz"
      echo "   downloading AdditionalMaps_$VERSION.tar.gz"
      download "$BASE_URL/AdditionalMaps_$VERSION.tar.gz" "$MAPS_TAR" || {
        echo "additional maps download failed (optional): re-run with --maps-tar FILE or --no-maps"; exit 1; }
    else
      [ -f "$DIR/Import/$(basename "$MAPS_TAR")" ] || cp "$MAPS_TAR" "$DIR/Import/"
    fi
    (cd "$DIR" && ./ImportAssets.sh)
    touch "$MARK"
  fi
fi

echo "== Python client"
if [ -x "$VENV/bin/python" ]; then
  TAG=$("$VENV/bin/python" -c 'import sys; print("cp%d%d" % sys.version_info[:2])')
  WHEEL=$(find "$DIR/PythonAPI/carla/dist" -maxdepth 1 -name "carla-$VERSION-$TAG-*linux*.whl" 2>/dev/null | head -1 || true)
  if [ -n "$WHEEL" ]; then
    "$VENV/bin/python" -m pip install -q "$WHEEL"
  else
    "$VENV/bin/python" -m pip install -q "carla==$VERSION"
  fi
  "$VENV/bin/python" -c 'import carla; print("   carla client OK:", carla.__file__)'
else
  echo "   venv $VENV not found: run scripts/setup.sh first, then re-run this script (it skips finished steps)"
fi

cat > "$ROOT/env.local.sh" <<EOF
# Generated by scripts/install_carla.sh (sourced by env.sh)
export CARLA_ROOT="$DIR"
EOF
echo "== done: CARLA_ROOT=$DIR (written to env.local.sh)"
echo "   runtime libraries if missing:  sudo apt install -y libomp5 xdg-user-dirs libvulkan1 vulkan-tools"
echo "   start the server:               $DIR/CarlaUE4.sh -quality-level=Epic      (or -RenderOffScreen)"
echo "   or everything at once:          scripts/run_carla_live.sh"
