#!/usr/bin/env python3
"""Generate CIE colorimetric tables and standard illuminant/emitter CSVs.

Source data: CIE 015:2018 tables as distributed by colour-science (BSD-3).
Outputs (checked into the repository so builds need no Python):
  src/spectrum/cie_tables.cpp          CIE 1931 2deg, CIE 1964 10deg CMFs, D65 (1 nm, 360-830 nm)
  data/spectra/emitters/*.csv          CIE LED / HP (high-pressure discharge) / FL illuminants
  data/spectra/colorchecker/*.csv      ColorChecker reflectances (BabelColor average)

Usage: python tools/gen_cie_tables.py   (requires `pip install colour-science numpy`)
"""
import os
import re
import numpy as np
import colour

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHAPE = colour.SpectralShape(360, 830, 1)


def fmt(arr):
    lines = []
    for i in range(0, len(arr), 8):
        lines.append("    " + ", ".join(f"{v:.9e}f" for v in arr[i:i + 8]) + ",")
    return "\n".join(lines)


def main():
    c31 = colour.MSDS_CMFS["CIE 1931 2 Degree Standard Observer"].copy().align(SHAPE)
    c64 = colour.MSDS_CMFS["CIE 1964 10 Degree Standard Observer"].copy().align(SHAPE)
    # D65 relative SPD computed from the CIE daylight basis (defined 300-830 nm).
    xy = colour.temperature.CCT_to_xy_CIE_D(6504 * 1.4388 / 1.4380)
    d65 = colour.sd_CIE_illuminant_D_series(xy).align(SHAPE)
    d65v = d65.values * (100.0 / d65[560])

    out = os.path.join(ROOT, "src", "spectrum", "cie_tables.cpp")
    with open(out, "w") as f:
        f.write("// Generated by tools/gen_cie_tables.py -- do not edit.\n")
        f.write("// CIE 015:2018 data (via colour-science). 1 nm spacing, 360..830 nm.\n")
        f.write('#include "spectral/spectrum/cie.h"\n\nnamespace spectral::cie {\n\n')
        n = len(SHAPE.wavelengths)
        f.write(f"static_assert(kSamples == {n});\n\n")
        for name, arr in [("x31", c31.values[:, 0]), ("y31", c31.values[:, 1]), ("z31", c31.values[:, 2]),
                          ("x64", c64.values[:, 0]), ("y64", c64.values[:, 1]), ("z64", c64.values[:, 2]),
                          ("d65", d65v)]:
            f.write(f"const float {name}[kSamples] = {{\n{fmt(arr)}\n}};\n\n")
        f.write("}  // namespace spectral::cie\n")
    print("wrote", out)

    emit_dir = os.path.join(ROOT, "data", "spectra", "emitters")
    os.makedirs(emit_dir, exist_ok=True)
    desc = {"HP1": "standard high-pressure sodium lamp", "HP2": "colour-enhanced high-pressure sodium lamp",
            "HP3": "metal halide lamp", "HP4": "metal halide lamp", "HP5": "ceramic metal halide lamp",
            "LED-B1": "phosphor-type LED 2733K", "LED-B2": "phosphor-type LED 2998K",
            "LED-B3": "phosphor-type LED 4103K", "LED-B4": "phosphor-type LED 5109K",
            "LED-B5": "phosphor-type LED 6598K", "LED-BH1": "hybrid LED 2851K",
            "LED-RGB1": "RGB LED 2840K", "LED-V1": "violet-pumped LED 2724K", "LED-V2": "violet-pumped LED 4070K",
            "FL2": "cool white fluorescent", "FL7": "broadband daylight fluorescent", "FL11": "narrow tri-band fluorescent"}
    for k, d in desc.items():
        sd = colour.SDS_ILLUMINANTS[k]
        path = os.path.join(emit_dir, "cie_" + k.lower().replace("-", "_") + ".csv")
        with open(path, "w") as f:
            f.write(f"# CIE illuminant {k}: {d}. Source: CIE 015:2018 via colour-science.\n")
            f.write("# Relative spectral power (arbitrary units). Defined 380-780 nm only; zero outside.\n")
            f.write("# extrapolation: zero\n")
            f.write("wavelength_nm,value\n")
            for w, v in zip(sd.wavelengths, sd.values):
                f.write(f"{w:g},{v:.6g}\n")
    print("wrote emitters")

    cc_dir = os.path.join(ROOT, "data", "spectra", "colorchecker")
    os.makedirs(cc_dir, exist_ok=True)
    cc = colour.SDS_COLOURCHECKERS["BabelColor Average"]
    names = list(cc.keys())
    wl = cc[names[0]].wavelengths
    with open(os.path.join(cc_dir, "colorchecker_babel.csv"), "w") as f:
        f.write("# X-Rite ColorChecker Classic, 24 patches, BabelColor average reflectance.\n")
        f.write("# Source: BabelColor (D. Pascale) via colour-science. 380-730 nm, 10 nm.\n")
        f.write("# extrapolation: clamp\n")
        f.write("wavelength_nm," + ",".join(re.sub(r"[^a-z0-9]+", "_", n.lower()).strip("_") for n in names) + "\n")
        for i, w in enumerate(wl):
            f.write(f"{w:g}," + ",".join(f"{cc[n].values[i]:.6g}" for n in names) + "\n")
    print("wrote colorchecker")


if __name__ == "__main__":
    main()
