#!/usr/bin/env python3
"""Writes APPROXIMATE placeholder material spectra into data/spectra/materials/.

These are hand-shaped curves with qualitatively correct features (e.g. the vegetation red edge,
iron absorption of green windshield glass). They are NOT measurements. Replace them with measured
data (e.g. USGS splib07, ECOSTRESS, supplier data sheets) before drawing quantitative conclusions.
Each file carries this warning in its header.
"""
import os
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "spectra", "materials")
L = np.arange(350.0, 1101.0, 10.0)


def sig(x, x0, w):
    return 1.0 / (1.0 + np.exp(-(x - x0) / w))


def gauss(x, mu, s):
    return np.exp(-0.5 * ((x - mu) / s) ** 2)


curves = {
    "approx_asphalt_dry": ("reflectance", 0.05 + 0.07 * (L - 350) / 750),
    "approx_asphalt_wet": ("reflectance", 0.025 + 0.03 * (L - 350) / 750),
    "approx_concrete": ("reflectance", 0.18 + 0.17 * sig(L, 500, 60) + 0.05 * (L - 350) / 750),
    "approx_vegetation_leaf": ("reflectance",
                               0.04 + 0.08 * gauss(L, 550, 30) + 0.46 * sig(L, 715, 12) - 0.02 * gauss(L, 670, 15)),
    "approx_grass_dry": ("reflectance", 0.06 + 0.25 * sig(L, 600, 70) + 0.1 * sig(L, 720, 20)),
    "approx_car_paint_white": ("reflectance", 0.82 - 0.25 * (1 - sig(L, 420, 15))),
    "approx_car_paint_black": ("reflectance", 0.04 + 0.01 * (L - 350) / 750),
    "approx_car_paint_red": ("reflectance", 0.05 + 0.65 * sig(L, 600, 12) + 0.05 * sig(L, 750, 40)),
    "approx_car_paint_blue": ("reflectance", 0.05 + 0.35 * gauss(L, 460, 35) + 0.30 * sig(L, 760, 30)),
    "approx_lane_marking_white": ("reflectance", 0.72 - 0.2 * (1 - sig(L, 420, 15))),
    "approx_lane_marking_yellow": ("reflectance", 0.08 + 0.62 * sig(L, 530, 12)),
    "approx_retroreflective_sheeting_white": ("reflectance", 0.80 - 0.2 * (1 - sig(L, 420, 15))),
    "approx_dashboard_black_pvc": ("reflectance", 0.035 + 0.02 * sig(L, 800, 60)),
    "approx_skin_light": ("reflectance",
                          0.25 + 0.35 * sig(L, 600, 15) - 0.06 * gauss(L, 545, 12) - 0.06 * gauss(L, 578, 10)
                          + 0.05 * sig(L, 700, 40) - 0.1 * sig(L, 950, 30)),
    # Internal transmittance of 5 mm green-tinted soda-lime glass (Fe2+ absorption band near 1000 nm).
    "approx_windshield_green_5mm": ("internal_transmittance",
                                    0.92 * gauss(L, 530, 380) - 0.35 * sig(L, 850, 90) - 0.08 * (1 - sig(L, 400, 15))),
    # Transmittance of an IR-reflective windshield coating (visible pass, NIR cut).
    "approx_windshield_ir_cut_coating": ("transmittance", 0.88 * sig(L, 405, 8) * (1 - 0.8 * sig(L, 720, 15))),
}


def main():
    os.makedirs(OUT, exist_ok=True)
    for name, (kind, v) in curves.items():
        v = np.clip(v, 0.0, 1.0)
        with open(os.path.join(OUT, name + ".csv"), "w") as f:
            f.write(f"# {name}: APPROXIMATE placeholder {kind} (hand-shaped curve, NOT a measurement).\n")
            f.write("# Replace with measured data before quantitative use. Generated by tools/gen_approx_materials.py\n")
            f.write("# extrapolation: clamp\n")
            f.write("wavelength_nm,value\n")
            for l, x in zip(L, v):
                f.write(f"{l:g},{x:.4f}\n")
    print("wrote", len(curves), "files to", OUT)


if __name__ == "__main__":
    main()
